# Generated by Django 5.2.14 on 2026-06-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='enquiry_photos/'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
