# Generated by Django 5.2.14 on 2026-06-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_enquiry_photo_alter_enquiry_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
