# Generated by Django 5.2.14 on 2026-06-16 17:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_alter_enquiry_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo'),
        ),
    ]
