# Generated by Django 5.2.14 on 2026-06-25 14:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_alter_enquiry_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('emoji', models.CharField(blank=True, default='📦', max_length=10)),
                ('category', models.CharField(choices=[('dress', 'Dress'), ('jwl', 'Jewellery'), ('shoe', 'Footwear'), ('beauty', 'Beauty'), ('home', 'Home'), ('kids', 'Kids'), ('other', 'Other')], default='other', max_length=20)),
                ('price', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='photo',
        ),
    ]
