# Generated by Django 5.2.14 on 2026-06-25 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0006_customer_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiry.enquiry'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
