# Generated by Django 5.2.14 on 2026-07-14 20:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0007_alter_order_customer_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo'),
        ),
    ]
